# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/balazs/Dropbox/HomeProjects/Raylite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/balazs/Dropbox/HomeProjects/Raylite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/balazs/Dropbox/HomeProjects/Raylite/CMakeFiles /home/balazs/Dropbox/HomeProjects/Raylite/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/balazs/Dropbox/HomeProjects/Raylite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/raylite

# Build rule for target.
bin/raylite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/raylite
.PHONY : bin/raylite

# fast build rule for target.
bin/raylite/fast:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/build
.PHONY : bin/raylite/fast

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/Plane.o: src/Plane.cpp.o

.PHONY : src/Plane.o

# target to build an object file
src/Plane.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Plane.cpp.o
.PHONY : src/Plane.cpp.o

src/Plane.i: src/Plane.cpp.i

.PHONY : src/Plane.i

# target to preprocess a source file
src/Plane.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Plane.cpp.i
.PHONY : src/Plane.cpp.i

src/Plane.s: src/Plane.cpp.s

.PHONY : src/Plane.s

# target to generate assembly for a file
src/Plane.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Plane.cpp.s
.PHONY : src/Plane.cpp.s

src/RayTracer.o: src/RayTracer.cpp.o

.PHONY : src/RayTracer.o

# target to build an object file
src/RayTracer.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/RayTracer.cpp.o
.PHONY : src/RayTracer.cpp.o

src/RayTracer.i: src/RayTracer.cpp.i

.PHONY : src/RayTracer.i

# target to preprocess a source file
src/RayTracer.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/RayTracer.cpp.i
.PHONY : src/RayTracer.cpp.i

src/RayTracer.s: src/RayTracer.cpp.s

.PHONY : src/RayTracer.s

# target to generate assembly for a file
src/RayTracer.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/RayTracer.cpp.s
.PHONY : src/RayTracer.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Sphere.o: src/Sphere.cpp.o

.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i

.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s

.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Triangle.o: src/Triangle.cpp.o

.PHONY : src/Triangle.o

# target to build an object file
src/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Triangle.cpp.o
.PHONY : src/Triangle.cpp.o

src/Triangle.i: src/Triangle.cpp.i

.PHONY : src/Triangle.i

# target to preprocess a source file
src/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Triangle.cpp.i
.PHONY : src/Triangle.cpp.i

src/Triangle.s: src/Triangle.cpp.s

.PHONY : src/Triangle.s

# target to generate assembly for a file
src/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/Triangle.cpp.s
.PHONY : src/Triangle.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bin/raylite.dir/build.make CMakeFiles/bin/raylite.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bin/raylite"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Plane.o"
	@echo "... src/Plane.i"
	@echo "... src/Plane.s"
	@echo "... src/RayTracer.o"
	@echo "... src/RayTracer.i"
	@echo "... src/RayTracer.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Triangle.o"
	@echo "... src/Triangle.i"
	@echo "... src/Triangle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

